ars_nouveau_machine_content=${ars_machine_content}
mekanism_extras_integration=${mekanism_extras_integration}
mekenergistics_integration=${mekenergistics_integration}
ae2_integration=${ae2_integration}
